### ISSUE TITLE
language server crashing within lint! given hcat input

### ISSUE THREAD

**Issue by mchristianl** [julia-vscode/CSTParser.jl#359] opened 2022-07-31 16:19 UTC
Hi,

The Julia language server crashes, given the following input file:

```julia
[ [let l = min((d-k),k); binomial(d-l,l); end; for k in 1:d-1] for d in 2:9 ]
```
I've tracked the issue down to

https://github.com/julia-vscode/CSTParser.jl/blob/v3.3.6/src/iterate.jl#L130

where an expression `x` arrives with 4 elements in its `x.trivia` part, where the implementation of `_vcat`

https://github.com/julia-vscode/CSTParser.jl/blob/v3.3.6/src/iterate.jl#L705

seems to assume at maximum two such elements.

For `x.trivia` I get

```
x.trivia[1] =   1:1   [
x.trivia[2] =   1:0   errortoken( CSTParser.UnexpectedToken)
  1:0    ]
x.trivia[3] =   1:2   [
x.trivia[4] =   1:0   errortoken( CSTParser.UnexpectedToken)
  1:0    ]
```

and `x` is

```
x =   1:77  hcat( )
  1:44   let(  new scope)
  1:18      1:2   OP: =( )
  1:2      l Binding(l(3 refs)) * 
  3:16     call( )
  3:5       min * 
  6:10      brackets( )
  6:8        call( )
  6:6         OP: -
  7:7         d
  8:8         k
 11:11      k
 19:35    block( )
 19:35     call( )
 19:26      binomial * 
 27:29      call( )
 27:27       OP: -
 28:28       d
 29:29       l * 
 30:30      l * 
 45:74   for(  new scope)
 45:54      1:0   OP: =( )
 45:46     k Binding(k(1 refs)) * 
 47:51     call( )
 47:47      OP: :
 48:48      INTEGER: 1
 49:51      call( )
 49:49       OP: -
 50:50       d
 51:51       INTEGER: 1
 55:70    block( )
 55:56     errortoken( )
 55:56      ]
 57:70     for(  new scope)
 57:65        1:0   OP: =( )
 57:58       d Binding(d:: (1 refs)) * 
 59:62       call( )
 59:59        OP: :
 60:60        INTEGER: 2
 61:62        INTEGER: 9
 66:66      block( )
 66:66       errortoken( )
 66:66        ]
```

the full error trace is

```
┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/error_handler.jl:15
ERROR: BoundsError: attempt to access 2-element Vector{CSTParser.EXPR} at index [3]
Stacktrace:
  [1] getindex
    @ ./array.jl:861 [inlined]
  [2] _vcat(x::CSTParser.EXPR, i::Int64)
    @ CSTParser.Iterating ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/CSTParser/src/iterate.jl:727
  [3] _getindex(x::CSTParser.EXPR, i::Int64)
    @ CSTParser.Iterating ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/CSTParser/src/iterate.jl:131
  [4] getindex(x::CSTParser.EXPR, i::Int64)
    @ CSTParser.Iterating ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/CSTParser/src/iterate.jl:6
  [5] collect_hints(x::CSTParser.EXPR, env::StaticLint.ExternalEnv, missingrefs::Symbol, isquoted::Bool, errs::Vector{Tuple{Int64, CSTParser.EXPR}}, pos::Int64) (repeats 2 times)
    @ StaticLint ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/StaticLint/src/linting/checks.jl:629
  [6] collect_hints(x::CSTParser.EXPR, env::StaticLint.ExternalEnv, missingrefs::Symbol)
    @ StaticLint ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/StaticLint/src/linting/checks.jl:605
  [7] mark_errors(doc::LanguageServer.Document, out::Vector{LanguageServer.Diagnostic})
    @ LanguageServer ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/LanguageServer/src/requests/textdocument.jl:124
  [8] lint!(doc::LanguageServer.Document, server::LanguageServerInstance)
    @ LanguageServer ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/LanguageServer/src/staticlint.jl:77
  [9] parse_all(doc::LanguageServer.Document, server::LanguageServerInstance)
    @ LanguageServer ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/LanguageServer/src/requests/textdocument.jl:118
 [10] textDocument_didOpen_notification(params::LanguageServer.DidOpenTextDocumentParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
    @ LanguageServer ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/LanguageServer/src/requests/textdocument.jl:17
 [11] (::LanguageServer.var"#98#99"{typeof(LanguageServer.textDocument_didOpen_notification), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.DidOpenTextDocumentParams)
    @ LanguageServer ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/LanguageServer/src/languageserverinstance.jl:262
 [12] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ JSONRPC ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/JSONRPC/src/typed.jl:67
 [13] run(server::LanguageServerInstance)
    @ LanguageServer ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/packages/LanguageServer/src/languageserverinstance.jl:382
 [14] top-level scope
    @ ~/.vscode-oss/extensions/julialang.language-julia-1.6.28/scripts/languageserver/main.jl:96
```

My language server is at v1.6.28.

Does this suffice for you to reproduce the issue or is some more information necessary?

kind regards,

**Comment by pfitzseb** [comment] 2022-07-31 17:25
Thanks for the reproducer! Should be fixed by https://github.com/julia-vscode/CSTParser.jl/pull/356/commits/e41b7851c4de7bfd3c6f13fd605b114b1f481067.

**Closed** 2022-08-01 09:28 UTC

**Comment by mchristianl** [comment] 2022-08-01 09:37
Thank you, it is working now!

**Comment by pfitzseb** [comment] 2022-08-01 09:51
Btw, I'd recommend writing
```
[ [let l = min((d-k),k); binomial(d-l,l); end for k in 1:d-1] for d in 2:9 ]
```
instead (no semi-colon after the `end`), because that works on all Julia versions (as opposed to only 1.7+).
